pipeline {
    agent any

    parameters {
        string(name: 'build_version', defaultValue: 'V1.0', description: 'Build version to use for Docker image')
    }

    environment {
        GIT_REPO_URL = 'https://github.com/Soulaimane99/devops-demo-project.git'
        GIT_REPO_NAME = 'devops-demo-project'
        GIT_USER_NAME = 'Soulaimane99'
        DOCKERHUB_REPO = 'soulaimane99/demo-java-app'
        SONAR_URL = 'http://sonarqube:9000'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-creds',
                    url: "${GIT_REPO_URL}"
            }
        }

        stage('Build and Test') {
            steps {
                sh 'ls -ltr'
                sh 'cd demo-java-app && mvn clean package'
            }
        }

        stage('Static Code Analysis') {
            steps {
                withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_AUTH_TOKEN')]) {
                    sh '''
                        cd demo-java-app
                        mvn sonar:sonar \
                          -Dsonar.login=$SONAR_AUTH_TOKEN \
                          -Dsonar.host.url=$SONAR_URL
                    '''
                }
            }
        }

        stage('Build and Push Docker Image') {
            environment {
                DOCKER_IMAGE = "${DOCKERHUB_REPO}:${build_version}"
            }
            steps {
                script {
                    sh "cd demo-java-app && docker build -t ${DOCKER_IMAGE} ."

                    def dockerImage = docker.image("${DOCKER_IMAGE}")
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub-creds') {
                        dockerImage.push()
                    }
                }
            }
        }

        stage('Update Deployment File') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github-creds', usernameVariable: 'GITHUB_USERNAME', passwordVariable: 'GITHUB_TOKEN')]) {
                    sh '''
                        git config user.email "soulaimane@example.com"
                        git config user.name "$GITHUB_USERNAME"

                        sed -i "s/tag: .*/tag: \\"${build_version}\\"/" helm/app/values.yaml

                        git add helm/app/values.yaml
                        git commit -m "Update deployment image to version ${build_version}" || echo "No changes to commit"

                        git push https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git HEAD:main
                    '''
                }
            }
        }
    }
}
