replicaCount: 1

image:
  repository: "docker.elastic.co/elasticsearch/elasticsearch"
  pullPolicy: IfNotPresent
  tag: "7.16.2"

appName: es
namespace: logging

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Limite mémoire JVM Elasticsearch
esJavaOpts: "-Xmx512m -Xms512m"

resources:
  requests:
    memory: "700Mi"
    cpu: "100m"
  limits:
    memory: "1Gi"
    cpu: "500m"

livenessProbe:
  httpGet:
    path: /
    port: http

readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
